apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-dhl-openshift
spec:
  revisionHistoryLimit: 0
  replicas: 4
  selector:
    matchLabels:
      app: hello-dhl-openshift
  template:
    metadata:
      labels:
        app: hello-dhl-openshift
    spec:
      containers:
        - name: main
          image: ghcr.io/ondrejsika/training-example
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: TEXT
              value: "Ahoj DHL!"
            - name: TEXT_SUFFIX
              value: v2
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              memory: 20Mi
              cpu: 20m
