services:
  redis:
    image: redis:8
    volumes:
      - redis-data:/data
  backend:
    build: ./backend
    image: ttl.sh/dhl/backend
    environment:
      REDIS: redis
  frontend:
    build: ./frontend
    image: ttl.sh/dhl/frontend
    environment:
      API_ORIGIN: http://backend:8000
    ports:
      - 80:3000

volumes:
  redis-data: