apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-dhl-from-cm
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - hello-dhl-from-cm.lab0.sikademo.com
      secretName: hello-dhl-from-cm-tls
  rules:
    - host: hello-dhl-from-cm.lab0.sikademo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-dhl-from-cm
                port:
                  number: 80
