apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ondrejsika-counter-with-values-object
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ondrejsika-counter-with-values-object
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sika-training-examples/2025-11-10_docker-kubernetes-dhl.git
    path: ./helm/counter
    helm:
      valuesObject:
        host: ondrejsika-counter-with-values-object.apps.training.germanywestcentral.aroapp.io
        backendVersion: v1
        environment: with-values-object
        ingressClassName: openshift-default
        ingressTlsDisable: true
