apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-dhl-with-keda
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hello-dhl-with-keda
  template:
    metadata:
      labels:
        app: hello-dhl-with-keda
    spec:
      containers:
        - name: main
          image: ghcr.io/ondrejsika/training-example
          ports:
            - containerPort: 80
          env:  
            - name: TEXT
              value: "Ahoj DHL!"
            - name: TEXT_SUFFIX
              value: v2
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              memory: 20Mi
              cpu: 20m
